version: "3.8"

services:
  # 1. Mesin WhatsApp (WAHA)
  waha:
    image: devlikeapro/waha
    restart: always
    environment:
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
      - WAHA_DASHBOARD_ENABLED=false
      - WAHA_API_KEY=abc123secretkeyQM8
      - WAHA_PRINT_QR=false
      # Print QR di logs dimatikan karena kita pakai web view
    ports:
      - "3000:3000"
    volumes:
      - waha_data:/app/.waha

  # 2. Mesin Bot (Aplikasi Python)
  bot_app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      - WAHA_BASE_URL=http://waha:3000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SUPER_ADMIN_WA=${SUPER_ADMIN_WA}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - waha

volumes:
  waha_data:
